# https://docs.aws.amazon.com/cli/latest/userguide/install-cliv2-mac.html
# Install to /usr/local/aws-cli

install:
	curl "https://awscli.amazonaws.com/AWSCLIV2.pkg" -o "AWSCLIV2.pkg"
	sudo installer -pkg AWSCLIV2.pkg -target /